### ISSUE TITLE
Evaluating trained model with KTH fails

### ISSUE THREAD

**Issue by rszeto** [rubenvillegas/iclr2017mcnet#2]
I am getting the following error when trying to evaluate a model that I trained:

```
Traceback (most recent call last):
  File "/home/szetor/Documents/video_prediction/iclr2017mcnet/src/test_kth.py", line 182, in <module>
    main(**vars(args))
  File "/home/szetor/Documents/video_prediction/iclr2017mcnet/src/test_kth.py", line 51, in main
    save_path = quant_dir+"results_model="+best_model+".npz"
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

I assume at some point before that line, you're supposed to set `best_model` to `"MCNET.model-<iter_num>"`, but that never happens. I suspect the same bug is in `test_ucf101.py`.

**Comment by rubenvillegas** [comment]
This has been fixed
